package com.siyu.mdm.custom.device.json

data class DeviceSettings(
    val screenCapture: Boolean,
    val unknownSource: Boolean,
    val multiWindow: Boolean,
    val notification: Boolean,
    val setupSearch: Boolean,
    val developer: Boolean,
    val fileShare: Boolean,
    val bluetoothFileTransfer: Boolean,
    val wifi: Boolean,
    val nfc: Boolean,
    val hotspot: Boolean,
    val sd: Boolean,
    val microphone: Boolean,
    val factory: Boolean,
    val safemode: Boolean,
    val multipleUsers: Boolean,
    val time: Boolean,
    val forcePassword: Boolean,
    val setPowerOnPassword: Boolean,
    val flight: Boolean,
    val shortMessageSend: Boolean,
    val id: Boolean,
    val apn: Boolean,
    val vpn: Boolean,
    val videoCam: Boolean,
    val fingerprint: Boolean,
    val usb: Boolean,
    val usbDebug: Boolean,
    val otgSwitch: Boolean,
    val workdayLockScreen: Boolean,
    val pullDown: Boolean,
    val powerSave: Boolean,
    val trafficSave: Boolean
)